version: '3'
services:
  app:
    build:
      context: .
      args:
        REACT_APP_API_HOST: "http://localhost:3010"
    volumes:
      - ./src:/app/src
    container_name: oteasy-client
    restart: always
    ports:
      - 3000:3000